career:
    path:     /
    defaults: { _controller: "myBundleictBundle:career:index" }

career_show:
    path:     /{id}/show
    defaults: { _controller: "myBundleictBundle:career:show" }

career_new:
    path:     /new
    defaults: { _controller: "myBundleictBundle:career:new" }

career_create:
    path:     /create
    defaults: { _controller: "myBundleictBundle:career:create" }
    requirements: { _method: post }

career_edit:
    path:     /{id}/edit
    defaults: { _controller: "myBundleictBundle:career:edit" }

career_update:
    path:     /{id}/update
    defaults: { _controller: "myBundleictBundle:career:update" }
    requirements: { _method: post|put }

career_delete:
    path:     /{id}/delete
    defaults: { _controller: "myBundleictBundle:career:delete" }
    requirements: { _method: post|delete }
    
career_count:
    path:     /{id}/count
    defaults: { _controller: "myBundleictBundle:career:count" }
